USE APP;

-- CREATE USERS

INSERT INTO `APP`.`Users`
VALUES (1,'THISISAHASH1','THISISAEMAIL','THISISANOTHERHASH1','UNAME1',NOW(),0,'','DE');

INSERT INTO `APP`.`Users`
VALUES (2,'THISISAHASH2','THISISAEMAIL','THISISANOTHERHASH2','UNAME2',NOW(),0,'','DE');

INSERT INTO `APP`.`Users`
VALUES (3,'THISISAHASH3','THISISAEMAIL','THISISANOTHERHASH3','UNAME3',NOW(),4,'','DE');

INSERT INTO `APP`.`Users`
VALUES (4,'THISISAHASH4','THISISAEMAIL','THISISANOTHERHASH4','UNAME4',NOW(),5,'','DE');

INSERT INTO `APP`.`Users`
VALUES (5,'THISISAHASH5','THISISAEMAIL','THISISANOTHERHASH5','UNAME5',NOW(),7,'','DE');

INSERT INTO `APP`.`Users`
VALUES (6,'THISISAHASH6','THISISAEMAIL','THISISANOTHERHASH6','UNAME6',NOW(),100,'','DE');

-- CREATE PUBLIC QUESTIONS

INSERT INTO `APP`.`PublicQuestions`
VALUES (1,'THISISAQUESTION','THIS IS ADD INFO',1,'',NOW(),NOW(),'DE',0,default);

INSERT INTO `APP`.`PublicQuestions`
VALUES (2,'THISISAQUESTION','THIS IS ADD INFO',3,'',NOW(),NOW(),'DE',0,default);

INSERT INTO `APP`.`PublicQuestions`
VALUES (3,'THISISAQUESTION','THIS IS ADD INFO',3,'',NOW(),NOW(),'DE',0,default);

-- CREATE ANSWERS PUBLIC QUESTION

INSERT INTO `APP`.`AnswersPublicQuestions`
VALUES (1,1,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPublicQuestions`
VALUES (2,1,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPublicQuestions`
VALUES (3,1,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPublicQuestions`
VALUES (4,2,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPublicQuestions`
VALUES (5,2,'THISISAANSWER');


-- CREATE PUBLIC QUESTIONS TO USERS

INSERT INTO `APP`.`PublicQuestionsToUsers`
VALUES(1,1,2);

INSERT INTO `APP`.`PublicQuestionsToUsers`
VALUES(1,2,3);

INSERT INTO `APP`.`PublicQuestionsToUsers`
VALUES(2,3,1);

INSERT INTO `APP`.`PublicQuestionsToUsers`
VALUES(2,4,1);

-- CREATE GROUPS
INSERT INTO `APP`.`Groups`
VALUES (1,NOW(),1,'THISISAGROUP','');

INSERT INTO `APP`.`Groups`
VALUES (2,NOW(),2,'THISISAGROUP','');

-- CREATE GROUPS TO USERS
INSERT INTO `APP`.`GroupsToUsers`
VALUES (1,1,default);

INSERT INTO `APP`.`GroupsToUsers`
VALUES (2,1,default);

INSERT INTO `APP`.`GroupsToUsers`
VALUES (1,2,3);

INSERT INTO `APP`.`GroupsToUsers`
VALUES (2,2,default);

INSERT INTO `APP`.`GroupsToUsers`
VALUES (1,3,default);

INSERT INTO `APP`.`GroupsToUsers`
VALUES (2,3,7);

-- CREATE PRIVATE QUESTIONS
INSERT INTO `APP`.`PrivateQuestions`
VALUES (1,'THISISAQUESTION','THISISAADDINFO',1,1,'',NOW(),NOW(),0,1,null,'DE',true,null,false);

INSERT INTO `APP`.`PrivateQuestions`
VALUES (2,'THISISAQUESTION','THISISAADDINFO',2,1,'',NOW(),NOW(),0,2,null,'DE',true,null,false);

INSERT INTO `APP`.`PrivateQuestions`
VALUES (3,'THISISAQUESTION','THISISAADDINFO',3,1,'',NOW(),NOW(),0,2,null,'DE',false,null,false);

INSERT INTO `APP`.`PrivateQuestions`
VALUES (4,'THISISAQUESTION','THISISAADDINFO',1,2,'',NOW(),NOW(),0,3,2,'DE',true,null,false);

INSERT INTO `APP`.`PrivateQuestions`
VALUES (5,'THISISAQUESTION','THISISAADDINFO',1,2,'',NOW(),NOW(),0,3,2,'DE',true,null,false);

-- CREATE ANSWER PRIVATE QUESTION
INSERT INTO `APP`.`AnswersPrivateQuestions`
VALUES(1,1,'THISISAANSWER');
INSERT INTO `APP`.`AnswersPrivateQuestions`
VALUES(6,2,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPrivateQuestions`
VALUES(2,2,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPrivateQuestions`
VALUES(3,3,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPrivateQuestions`
VALUES(4,4,'THISISAANSWER');

INSERT INTO `APP`.`AnswersPrivateQuestions`
VALUES(5,5,'THISISAANSWER');